### ISSUE TITLE
Accessing private services

### ISSUE THREAD

**Issue by umpirsky** [SymfonyTest/symfony-bundle-test#18]
This means that in tests accessing private services will not be caught as an error? I find this dangerous.

**Comment by Nyholm** [comment]
Oh, very true. Can you update the documentation to warn about this?

**Comment by umpirsky** [comment]
Done https://github.com/SymfonyTest/symfony-bundle-test/pull/19.

Is there a way to detect if service is private and skip it in the smoke test?

**Comment by Nyholm** [comment]
Not sure what you mean. You decide yourself what services you will "force make" public. And you decide what services you want to test.

**Comment by umpirsky** [comment]
Yes, but when you write smoke test, like this for example https://gist.github.com/Maff-/c9d2c1592a746da85d5b, you iterate Symfony private services and vendors private services (e.g. `argument_metadata_factory`, `annotation_reader`... a number of them). For all this services `$container->has($id)` is `true`, but `$container->get($id)` throws deprecation that service is private and you should not access it (Symfony 3.4).

I don't see elegant solution for this.

**Comment by Nyholm** [comment]
When I testing my third party bundles I always do something like this: 
https://github.com/SymfonyTest/symfony-bundle-test#write-a-test

Example: https://github.com/php-translation/symfony-bundle/blob/0.6.1/Tests/Functional/BundleInitializationTest.php

**Comment by umpirsky** [comment]
It's not generic. I have a smoke test that iterates `$container->getServiceIds()`.

**Comment by Nyholm** [comment]
Hm... So you want to test AppBundle. Or all services in the kernel. And you just want to instantiate the services, right?

**Comment by umpirsky** [comment]
Yes, all public services in the kernel. But I get private too, and can't distinguish them.

**Comment by Nyholm** [comment]
For that you just need to build the container, right? 

Upon building the container Symfony will try to resolve all dependencies.

**Comment by umpirsky** [comment]
The test is as simple as:

```php
class GenericServicesTest extends TestCase
{
    public function testServiceInstantiation()
    {
        foreach ($container->getServiceIds() as $serviceId) {
            $this->assertNotNull($client->getContainer()->get($serviceId));
        }
    }
}
```

Container is already built and everything works fine until you enable deprecations.

Then you get:

```
Remaining deprecation triggered by GenericServicesTest::testServiceInstantiation:
    The "argument_metadata_factory" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.
```

I was trying with:

```diff
class GenericServicesTest extends TestCase
{
    public function testServiceInstantiation()
    {
        foreach ($container->getServiceIds() as $serviceId) {
+            if (!$container->has($serviceId)) {
+                continue;
+            }
+            
            $this->assertNotNull($client->getContainer()->get($serviceId));
        }
    }
}
```

But `has()` returns true to private services as well.

**Comment by Nyholm** [comment]
Interesting. 
I just looked at the source. Maybe you could create your own container that extends `Container`. That would allow you to extract all public services and aliases.

**Comment by umpirsky** [comment]
Yes, I was thinking same, do that only in test env.

**Comment by umpirsky** [comment]
Fixed with:

```diff
-        foreach ($container->getServiceIds() as $serviceId) {
+        foreach (array_diff($container->getServiceIds(), array_keys($container->getRemovedIds())) as $serviceId) {
```

**Comment by Nyholm** [comment]
Great!

**Comment by Nyholm** [comment]
On other news: https://github.com/symfony/symfony/pull/26499
