### ISSUE TITLE
Compatibility with FrameworkBundle Test Traits

### ISSUE THREAD

**Issue by chapterjason** [SymfonyTest/symfony-bundle-test#39]
I just noticed that the `BaseBundleTestCase`  class is not compatible with the FrameworkBundle AssertionTraits.

In the trait `MailerAssertionsTrait` the [`getContainer`](https://github.com/symfony/symfony/blob/c8f37996f648bcd18c8fe0cb60cba0e6a0b7c6d9/src/Symfony/Bundle/FrameworkBundle/Test/MailerAssertionsTrait.php#L121) function is statically called, cause it is expected that the trait will be used in the `KernelTestCase` which have all the kernel and functions static.

Unfortunately the `BaseBundleTestCase` uses [non-static variables and functions](https://github.com/chapterjason/symfony-bundle-test/blob/bdfa9c7f0b3beba317745c7026e05b8614a8b6dc/src/BaseBundleTestCase.php#L49) and causes errors like these:

```
Error : Non-static method Nyholm\BundleTest\BaseBundleTestCase::getContainer() cannot be called statically
 /[...]/vendor/symfony/framework-bundle/Test/MailerAssertionsTrait.php:121
 /[...]/vendor/symfony/framework-bundle/Test/MailerAssertionsTrait.php:25
 /[...]/Tests/ExampleTest.php:159
```

I see three possible solutions:

1. We change the functions and variables to static, which would be a breaking change.
2. We serve custom traits with the same functionality which uses `$this`, but this also means more maintenance.
3. Combination of 1 and 2. We first serve custom traits to avoid a breaking change and change to static in version 2.0.

// EDIT
Also noticed that the KernelTextCase returns the `test.service_container` to allow access to private services.

**Comment by Nyholm** [comment]
Hm.. I added that method in the Symfony code base. 

What about removing it from `BaseBundleTestCase`? That will require a new major version, but it is in the correct direction.

**Comment by chapterjason** [comment]
I took a closer look and yes, this could be a good idea.

I have already tested how it is usable:

```php
<?php

namespace SoureCode\Bundle\Token\Tests;

use DAMA\DoctrineTestBundle\DAMADoctrineTestBundle;
use Doctrine\Bundle\DoctrineBundle\DoctrineBundle;
use Nyholm\BundleTest\AppKernel;
use Stof\DoctrineExtensionsBundle\StofDoctrineExtensionsBundle;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use MyCustomBundle;

abstract class MyAbstractBundleTestCase extends KernelTestCase
{

    protected static function createKernel(array $options = [])
    {
        KernelTestCase::$class = AppKernel::class;

        /**
         * @var AppKernel $kernel
         */
        $kernel = parent::createKernel($options);

        $kernel->addBundle(DoctrineBundle::class);
        $kernel->addBundle(DAMADoctrineTestBundle::class);
        $kernel->addBundle(StofDoctrineExtensionsBundle::class);
        $kernel->addBundle(MyCustomBundle::class);
        $kernel->addConfigFile(__DIR__.'/config.yml');

        return $kernel;
    }
}
```

To use it like this we need to take some changes in the `AppKernel`.

- The constructor is not compatible with the `createKernel` implementation in the `KernelTestCase`
   https://github.com/SymfonyTest/symfony-bundle-test/blob/bcf6a3a7d590f1ff804f15aa51a4251c0575f3d0/src/AppKernel.php#L51
   ```diff
   -    public function __construct($cachePrefix)
   +    public function __construct(string $environment, bool $debug)
   ```
- The cache prefix shouldn't be the environment.
   https://github.com/SymfonyTest/symfony-bundle-test/blob/bcf6a3a7d590f1ff804f15aa51a4251c0575f3d0/src/AppKernel.php#L54
   I think we could add a setter for that and set the default value to `uniqid('cache')`?
   https://github.com/SymfonyTest/symfony-bundle-test/blob/bcf6a3a7d590f1ff804f15aa51a4251c0575f3d0/src/BaseBundleTestCase.php#L73
