### ISSUE TITLE
The 1.8.1 releases triggers a deprecation when ensureKernelShutdown is called with a non-booted kernel

### ISSUE THREAD

**Issue by stof** [SymfonyTest/symfony-bundle-test#61]
If a kernel has been created but not booted, `BaseBundleTestCase::ensureKernelShutdown` triggers a deprecation warning when accessing `getContainer`. Ideally, it should skip the whole logic as the kernel is not booted.

This is especially an issue given that `BaseBundleTestCase::bootKernel()` starts by calling `ensureKernelShutdown`

**Comment by Nyholm** [comment]
Fixed by #64. 

Is the 1.x branch ready for a release?

**Comment by chapterjason** [comment]
@Nyholm Nothing to add from my side, both issues are fixed. 👍🏼 

Thank you @stof

**Comment by Nyholm** [comment]
We just release 2.0, this should all be fixed there.
