### ISSUE TITLE
1.8.2 compatible with Symfony 6?

### ISSUE THREAD

**Issue by dkarlovi** [SymfonyTest/symfony-bundle-test#65]
Looking at the release, it says it's compatible with Symfony 6. But with 1.8.2 installed I'm still getting:

```
Fatal error: Declaration of         
     Nyholm\BundleTest\AppKernel::getProjectDir() must be compatible with     
     Symfony\Component\HttpKernel\Kernel::getProjectDir(): string in          
     /project/vendor/nyholm/symfony-bundle-test/src/AppKernel.php on line 94
```

I can see the signatures were updated in master, but not in 1.x. Is 1.x meant to be compatible with Symfony 6?

**Comment by chapterjason** [comment]
I created a small reproducer and also wondered, but figured out why:

- https://github.com/SymfonyTest/symfony-bundle-test/commit/b3e6ae4fe3abe502fd9d93a808457d86119cdeb6 : We added compatibility, which unfortunately caused problems https://github.com/SymfonyTest/symfony-bundle-test/issues/60
- https://github.com/SymfonyTest/symfony-bundle-test/commit/dbdfb2697e229d447230369f6c1aac9fb5d7750f : We removed the non compatible php5 code cause of the issue.
- https://github.com/SymfonyTest/symfony-bundle-test/commit/afa5c98b3e3e9f3bd624b69d9b8070faee068d01 : We added back the return type and the compatibility, which isn't released yet.

I'm not sure if the 1.9 will be coming or the 2.0 will released cause of a larger rework.

/ping @Nyholm I think we should check if we are ready now with Symfony 6.0,  add PHP 8.1 and Symfony 6.1 in our tests and release 2.0 if everything works fine. I use the dev-master for several days now and it's working great. #55

**Comment by dkarlovi** [comment]
@chapterjason we should at least release 1.8.3 to remove Symfony 6 from `composer.json` as being supported? Currently it's allowing Symfony 6 component which it conflicts with.

**Comment by DoctorBryson** [comment]
Breaking changes shouldn't be expected in a minor version update, right?

**Comment by dkarlovi** [comment]
@DoctorBryson I've updated to `dev-master` as @chapterjason suggested, it was a very small tweak for my project so not a real issue for me. I can suggest submitting a PR which removes Symfony 6 from composer.json, this would be the smallest possible action which fixes the current situation.

**Comment by bocharsky-bw** [comment]
Looks like `AppKernel` was removed completely in master, but it exists in the latest release 1.8.2 and as the error message in this issue description says it's not compatible with the base `Symfony\Component\HttpKernel\Kernel`. I think this bundle needs another release, 1.8.3, that will bring compatibility between `Nyholm\BundleTest\AppKernel` and `Symfony\Component\HttpKernel\Kernel`

**Comment by sirolad** [comment]
For now, i had to downgrade to 1.8.1 for Symfony 6

**Comment by Nyholm** [comment]
We just release 2.0.0 with support for sf 4, 5 and 6
