### ISSUE TITLE
Release 2.0

### ISSUE THREAD

**Issue by Nyholm** [SymfonyTest/symfony-bundle-test#68]
Do we have any current blockers?

**Comment by chapterjason** [comment]
Hey @Nyholm 

I don't have anything on my list.

**Comment by Nyholm** [comment]
I testing things now. I see that it is not possible to not clear cache on Kernel::shutdown. Ie, I cannot test my bundles behaviour on Kernel reboot (Im doing that in Happyr service mocking). 

Could we add a parameter or something? Or an argument to `TestKernel::shutdown()`? That way I could override TestKernel to get this feature.
