### ISSUE TITLE
Release notes changelog link leads to 404

### ISSUE THREAD

**Issue by andrew-demb** [SymfonyTest/symfony-bundle-test#70]
Just to mention for a bit better release notes for future releases :)

Release notes: https://github.com/SymfonyTest/symfony-bundle-test/releases/tag/2.0.0

Broken link: https://github.com/SymfonyTest/symfony-bundle-test/blob/2.0.0/Changelog.md
Actual link: https://github.com/SymfonyTest/symfony-bundle-test/blob/2.0.0/CHANGELOG.md

**Comment by chapterjason** [comment]
@andrew-demb Thanks, fixed. :)
