### ISSUE TITLE
Why was PublicServicePass removed in v2?

### ISSUE THREAD

**Issue by loevgaard** [SymfonyTest/symfony-bundle-test#72]
Thanks for this great package 🎉 

Why was https://github.com/SymfonyTest/symfony-bundle-test/blob/1.x/src/CompilerPass/PublicServicePass.php removed in v2? If I want to test services that are only used by users of the bundle they are removed by default in Symfony and hence I cannot test them using this package. If I mark them public with the old `PublicServicePass` then I can.

Can you elaborate on this? Am I missing something? :)

**Comment by chapterjason** [comment]
Hey @loevgaard, it was removed in #48 as Symfony provides the `test.service_container` which gives you access to private services.

https://symfony.com/doc/current/testing.html#retrieving-services-in-the-test

**Comment by loevgaard** [comment]
Hi, @chapterjason 

Yes, but it doesn't give me access to removed services. See https://github.com/symfony/symfony/blob/6.2/src/Symfony/Bundle/FrameworkBundle/Test/TestContainer.php#L19-L23

**Comment by chapterjason** [comment]
Yes, that is right.

> If you need to test private services that have been removed (those who are not used by any other services), you need to declare those private services as public in the config/services_test.yaml file.

IMO It is better to explicitly set only the neccessary services public in a separate file and load it with [`addTestConfig`](https://github.com/SymfonyTest/symfony-bundle-test/blob/ac04570711af15a66b85a0ebff700222f98a0814/src/TestKernel.php#L92).

**Comment by loevgaard** [comment]
That may be right. I find it easier to do with the compiler pass, but yes your way is more explicit. Thanks for your quick response!
