### ISSUE TITLE
BaseBundleTestCase removal was not documented

### ISSUE THREAD

**Issue by rvanlaak** [SymfonyTest/symfony-bundle-test#73]
In https://github.com/SymfonyTest/symfony-bundle-test/commit/1ea1ed9766606c56ad0f72b27a34b94dbd558770 the BaseBundleTestCase was removed, but that was not documented on the CHANGELOG.

As it was part of /src before in 1.x, maybe the preferred approach on how to upgrade to 2.x can get documented as well?

**Comment by loevgaard** [comment]
> maybe the preferred approach on how to upgrade to 2.x can get documented as well?

In a library this simple it's probably better to just rewrite your test to match the README?

**Comment by rvanlaak** [comment]
Yes, in the upgrade process that is how we fixed this, so I'm definitely not against the fact that BaseBundleTestCase was removed (composition > inheritance 👍 😉).
